version: "3.8"

services:
  backend:
    container_name: be-api
    build:
      context: ./${BACKEND_DIR}/
      dockerfile: Dockerfile
      target: PROD
    volumes:
      - ./${BACKEND_DIR}:/app
    ports:
      - "${BACKEND_PORT}:4000"

  frontend:
    container_name: fe-client
    build:
      context: ./${FRONTEND_DIR}/
      dockerfile: Dockerfile
      target: PROD
    volumes:
      - ./${FRONTEND_DIR}/src:/app/src
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend