FROM node:18.14-alpine AS DEV

WORKDIR /app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

USER node

FROM node:18.14-alpine AS BUILD

WORKDIR /app

COPY --chown=node:node package*.json ./

COPY --chown=node:node --from=DEV /app/node_modules ./node_modules

COPY --chown=node:node . .

RUN npm run build

ENV NODE_ENV production

RUN npm ci --only=production && npm cache clean --force

USER node

FROM node:18.14-alpine AS PROD

COPY --chown=node:node --from=BUILD /app/package.json ./package.json
COPY --chown=node:node --from=BUILD /app/node_modules ./node_modules
COPY --chown=node:node --from=BUILD /app/dist ./dist

CMD [ "node", "dist/main.js" ]